feat: this post run may work

diff --git a/.github/actions/cloudflare-ip-manager/action.yml b/.github/actions/cloudflare-ip-manager/action.yml
--- a/.github/actions/cloudflare-ip-manager/action.yml
+++ b/.github/actions/cloudflare-ip-manager/action.yml
@@ -72,10 +72,10 @@ runs:
       with:
         post: |
           rule_id=${{ env.rule_id }}
-          response=$(curl --request DELETE \
+          status_code=$(curl --request DELETE \
             --url https://api.cloudflare.com/client/v4/zones/${{ inputs.cf_zone_id }}/firewall/access_rules/rules/$rule_id \
             --header 'Content-Type: application/json' \
-            --header 'Authorization: Bearer ${{ inputs.cf_api_key }}')
-          echo "Delete Response: $response"
-          success=$(echo $response | jq -r '.success')
-          [ "$success" != "true" ] && echo "Failed to delete rule with ID $rule_id" && exit 1 || echo "Successfully deleted rule with ID $rule_id"
+            --header 'Authorization: Bearer ${{ inputs.cf_api_key }}' \
+            -o /dev/null -w '%{http_code}')
+          echo "Status Code: $status_code"
+          [ "$status_code" -ge 200 ] && [ "$status_code" -lt 300 ] && echo "Successfully deleted rule with ID $rule_id" || echo "Failed to delete rule with ID $rule_id; Status Code: $status_code" && exit 1e rule with ID $rule_id; Status Code: $status_code" && exit 1
